### ISSUE TITLE
How to fix this issue:An error occurred while processing your request.

### ISSUE THREAD

**Issue by leegang** [dabear/LibreOOPWeb#1]
How to fix this issue:An error occurred while processing your request.
<img width="1122" alt="WechatIMG39" src="https://user-images.githubusercontent.com/2744278/70046736-980d2c80-1601-11ea-8d76-cfc0af97b1b6.png">

and how to config the NS_Host and Mongo_url

**Comment by dabear** [comment]
There is no support on this project. debug it in visual studio
